# Generated by Django 3.0.4 on 2020-05-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Kanji/')),
                ('character', models.CharField(max_length=100)),
                ('onyomi', models.CharField(blank=True, max_length=100)),
                ('kunyomi', models.CharField(blank=True, max_length=100)),
                ('meaning', models.TextField()),
            ],
            options={
                'verbose_name': 'Kanji',
                'verbose_name_plural': 'Kanji',
            },
        ),
    ]
