# Generated by Django 3.0.4 on 2020-05-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanji',
            name='image',
        ),
    ]
